#
# Run via up.sh
# Deadline 10.1.3.6 has a bug which requires IPv6 
# up.sh/down.sh creatinging destroying ipv6 network
# 
version: "3.7"

services:

  # deadline mongo database
  mongo:
    image: mongo
    ports:
      - "27017"
    container_name: deadline-mongo
    networks:
      dockernet:

  
  # deadline maya slave 
  deadline-slave1:
    container_name: deadline-slave1
    hostname: maya-slave1
    image: 'deadline10-client-maya2019'
    volumes:
        - type: volume
          source: deadline-volume
          target: /mnt/DeadlineRepository10
        - ./share:/share
    networks:
      dockernet:          
    entrypoint: ./deadlinelauncher
  
    # Expose REST API
  deadline-webservice:
    container_name: deadline-webservice
    hostname: deadline-webservice
    image: '${IMAGE}'
    ports:
      - "8082:8082"
    volumes:
      - type: volume
        source: deadline-volume
        target: /mnt/DeadlineRepository10
    networks:
      dockernet:
    entrypoint: ./deadlinewebservice

# Expose DeadlineRepository10 as a public network share
  deadline-samba:
    container_name: deadline-samba
    hostname: deadline-samba
    image: dperson/samba
    ports:
      - "139:139"
      - "445:445"
    volumes:
      - type: volume
        source: deadline-volume
        target: /share
    networks:
      dockernet:
      
    command: -s "DeadlineRepository10;/share;yes;no;yes;all;none;all"
        

    

#Externally created deadline-volume populated by install.sh
volumes:
  deadline-volume:
    external: true
  
# deadline 10.1.3.6 deadline has a bug which requires ipv6
# As version 3 compose yml does not support ipv6 yet creating/tearing down 
# ipv6 dockernet create/destroyed externally as part of up.sh and down.sh

networks:
    dockernet: