#
# Run via up.sh
# Deadline 10.1.3.6 has a bug which requires IPv6 
# up.sh/down.sh creatinging destroying ipv6 network
# 
version: "3.7"

services:

  # deadline mongo database
  mongo:
    image: mongo
    ports:
      - "27017:27017"
    container_name: deadline-mongo
    networks:
      dockernet:

  
  # deadline maya slave 
  maya-worker1:
    container_name: maya-worker1
    hostname: maya-worker1
    image: 'deadline10-client-maya2019'
    volumes:
        - type: volume
          source: deadline-volume
          target: /mnt/DeadlineRepository10
        - ./share:/share
    networks:
      dockernet:          
    entrypoint: ./deadlinelauncher
   
  
  # deadline configurator sets up spot pool, aws-fleet and adds maya 
  deadline-configurator:
    container_name: deadline-configurator
    hostname: deadline-configurator
    image: 'deadline10-client-maya2019'
    volumes:
        - type: volume
          source: deadline-volume
          target: /mnt/DeadlineRepository10
        - ./share:/share
        - type: bind
          source: ${DOCKER_HOST_DOCKER_DEADLINE_SCRIPTS_PATH}
          target: /scripts
    networks:
      dockernet:        
    entrypoint: /scripts/deadline_configurator.sh
    

  
    # Expose REST API
  deadline-webservice:
    container_name: deadline-webservice
    hostname: deadline-webservice
    image: '${IMAGE}'
    ports:
      - "8082:8082"
    volumes:
      - type: volume
        source: deadline-volume
        target: /mnt/DeadlineRepository10
    networks:
      dockernet:
    entrypoint: ./deadlinewebservice


# Expose DeadlineRepository10, installers and scripts as a public network shares
  deadline-samba:
    container_name: deadline-samba
    hostname: deadline-samba
    image: dperson/samba
    ports:
      - "139:139"
      - "445:445"
    volumes:
      - type: volume
        source: deadline-volume
        target: /share-repo
      - type: bind
        source: ${DOCKER_HOST_DOCKER_DEADLINE_INSTALLER_PATH}
        target: /share-installers
      - type: bind
        source: ${DOCKER_HOST_DOCKER_DEADLINE_SCRIPTS_PATH}
        target: /share-scripts

    networks:
      dockernet:

    command: -s "DeadlineRepository10;/share-repo;yes;no;yes;all;none;all" -s "Deadline10installers;/share-installers;yes;no;yes;all;none;all" -s "scripts;/share-scripts;yes;no;yes;all;none;all"

  # deadline pulse has to wait before it start - currently waiting mayaslave1 
  deadline-pulse:
    container_name: deadline-pulse
    hostname: deadline-pulse
    image: 'deadline10-client-maya2019'
    depends_on: 
      [maya-worker1]
    volumes:
        - type: volume
          source: deadline-volume
          target: /mnt/DeadlineRepository10
        - ./share:/share
    networks:
      dockernet:        
    entrypoint: ./deadlinepulse --nogui
    
#Externally created deadline-volume populated by install.sh
volumes:
  deadline-volume:
    external: true
  
# deadline 10.1.3.6 deadline has a bug which requires ipv6
# As version 3 compose yml does not support ipv6 yet creating/tearing down 
# ipv6 dockernet create/destroyed externally as part of up.sh and down.sh

networks:
    dockernet: